// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwium3.Models;

namespace kolokwium3.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200625070843_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kolokwium3.Models.Artist", b =>
                {
                    b.Property<int>("IdArtist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdArtist");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("kolokwium3.Models.ArtistEvent", b =>
                {
                    b.Property<int>("IdArtist")
                        .HasColumnType("int");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int?>("ArtistIdArtist")
                        .HasColumnType("int");

                    b.Property<int?>("EventIdEvent")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformanceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdArtist", "IdEvent");

                    b.HasIndex("ArtistIdArtist");

                    b.HasIndex("EventIdEvent");

                    b.ToTable("ArtistEvents");
                });

            modelBuilder.Entity("kolokwium3.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEvent");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("kolokwium3.Models.EventOrganiser", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int>("IdOrganiser")
                        .HasColumnType("int");

                    b.Property<int?>("EventIdEvent")
                        .HasColumnType("int");

                    b.Property<int?>("OrganiserIdOrganiser")
                        .HasColumnType("int");

                    b.HasKey("IdEvent", "IdOrganiser");

                    b.HasIndex("EventIdEvent");

                    b.HasIndex("OrganiserIdOrganiser");

                    b.ToTable("EventOrganisers");
                });

            modelBuilder.Entity("kolokwium3.Models.Organiser", b =>
                {
                    b.Property<int>("IdOrganiser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdOrganiser");

                    b.ToTable("Organisers");
                });

            modelBuilder.Entity("kolokwium3.Models.ArtistEvent", b =>
                {
                    b.HasOne("kolokwium3.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistIdArtist");

                    b.HasOne("kolokwium3.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventIdEvent");
                });

            modelBuilder.Entity("kolokwium3.Models.EventOrganiser", b =>
                {
                    b.HasOne("kolokwium3.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventIdEvent");

                    b.HasOne("kolokwium3.Models.Organiser", "Organiser")
                        .WithMany()
                        .HasForeignKey("OrganiserIdOrganiser");
                });
#pragma warning restore 612, 618
        }
    }
}
